image: python:3.8

test:
  stage: test
  script:
  - pip install -U sphinx
  - pip install sphinx_rtd_theme
  - pip install sphinxcontrib-bibtex
  - pip install sphinx-math-dollar
  - pip install myst_nb
  - pip install sphinx-copybutton
  - sphinx-build -b html docs public
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  script:
  - pip install -U sphinx
  - pip install sphinx_rtd_theme
  - pip install sphinxcontrib-bibtex
  - pip install sphinx-math-dollar
  - pip install myst_nb
  - pip install sphinx-copybutton
  - sphinx-build -b html docs public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

# # TODO: Add linter if refactoring is finished.!
# black:
#   only:
#       - master
#       - merge_requests
#   stage: test
#   image: registry.gitlab.com/pipeline-components/black:latest
#   script:
#     - black --check --verbose .
