name: Lint

on: [push]

jobs: 
  lint:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2
      - run: |
          pip install black
          python -m black . --check --diff