name: Build examples

# TODO change this before merge
on: [push]
# on:
#   pull_request:
#     branches:
#       - master
#       - main

jobs:
  build:
    name: Build project
    runs-on: [self-hosted, linux]
    # TODO: fix authentication in container
    # container: 
    #   image: python:latest
    steps:
    - uses: actions/checkout@v3
    - name: setup python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10' 
        cache: 'pip' # caching pip dependencies
        cache-dependency-path: setup.py
    - name: install dependencies
      run: pip install -e .
    - name: run hello world
      run: echo "Hello World"
    # TODO save artifacts
    # - name: upload artifacts
    #   uses: actions/upload-artifacts@v3
    #   with:
    #     name: figures
    #     path: TODO